name: Update artifact files for renovate
on:
  pull_request:
    branches: 'renovate*'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  update-artifact-files:
    if: ${{ github.actor == 'renovate[bot]' }}
    name: Update artifact files for renovate
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pod install
        run: pod install
      - name: Auto commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update artifact files (Podfile.lock)
          file_pattern: 'Podfile*'
