name: Update artifact files for renovate
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  update-artifact-files:
    if: ${{ github.actor == 'renovate[bot]' }}
    name: Update artifact files for renovate
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pod install
        run: pod install
      - name: Auto commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote -v
          git add .
          git commit -m "Update artifact files"
          git push origin renovate/firebaseinstallations
