name: Pod install after renovatebot
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pod-install:
    if: ${{ github.actor == 'renovate[bot]' }}
    name: Pod install
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Pod install
          run: pod install
        - name: Auto commit and push
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: Commit Podfile.lock
            
