name: Update artifact files for renovate
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled

jobs:
  update-artifact-files:
    name: Update artifact files for renovate
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout ${{ github.head_ref || github.ref_name }} 
          echo ${{ github.head_ref || github.ref_name }} 
          echo 'hello' > hello.txt
          git add .
          git commit -m "Update artifact files"
          git push
