name: Renovate post install
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
jobs:
  update-artifact-files:
    if: ${{ github.actor == 'renovate[bot]' }}
    name: Update artifact files for renovate[bot]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Pod install
        run: pod install
      - name: Auto commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update artifact files
          file_pattern: 'Podfile*'
  ci-ios:
    name: Check spell
    needs: update-artifact-files
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/ci_ios.yml

  ci_pr:
    name: Check title
    needs: ci-ios
    permissions:
      contents: read
      issues: read
      pull-requests: write
      statuses: write
    uses: ./.github/workflows/ci_pr.yml
