name: Renovate post install
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled
jobs:
  update-artifact-files:
    if: ${{ github.actor == 'renovate[bot]' }}
    name: Update artifact files for renovate[bot]
    runs-on: macos-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          permissions: "actions:write"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Pod install
        run: pod install
      - name: Auto commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update artifact files
          file_pattern: 'Podfile*'
