name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - run: |
          echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
    
