name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Expose env
        run: |
          echo ${{ secrets.ENV }} > .env
          cat .env
      - run: |
          echo ${{ env.APP_ID }}
