name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Expose env
        run: |
          echo ${{ secrets.ENV }} > .env
      - uses: falti/dotenv-action@v1.1.3
      - run: |
          echo ${{ env.APP_ID }}
