name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Generate .env file
        run: echo "${{ secrets.ENV }}" > .env
      - name: Load .env file
        id: dotenv
        uses: falti/dotenv-action@v1.1.3
      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ steps.dotenv.outputs.GITHUB_APP_ID }}
          application_private_key: ${{ secrets.GH_APPS_PRIVATE_KEY_PEM }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Install Ruby, bundler, fastlane and other dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Comment on PR
        run: bundle exec fastlane update_title issue_id:4 token:"${{ steps.get_workflow_token.outputs.token }}"
