name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Generate .env
        run: |
          echo ${{ secrets.ENV }} > .env
      - name: Load .env
        id: dotenv
        uses: falti/dotenv-action@v1.1.3
      - run: |
          echo ${{ steps.dotenv.outputs.APP_ID }}
      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ steps.dotenv.outputs.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Install Ruby, bundler, fastlane and other dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      - name: Comment on PR
        run: bundle exec fastlane ios add_comment pull_request_id:"${{ github.event.pull_request.number }}" token:"${{ steps.get_workflow_token.outputs.token }}" comment:"This PR is linked to EB-123942."
