name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Generate .env
        run: |
          echo ${{ secrets.ENV }} > .env
      - name: Load .env
        id: dotenv
        uses: falti/dotenv-action@v1.1.3
      - run: |
          echo ${{ steps.dotenv.outputs.APP_ID }}
