name: Test
on:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - run: |
          echo "${{ secrets.ENV }}" >> $GITHUB_ENV
          echo ${{ env.APP_ID}}
    
